spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/customer_app
    username: root
    password:
logging:
  file:
    name: log.txt
  level:
    root: debug
    org.springframework.web : info